### ISSUE TITLE
Different column widths in the same grid

### ISSUE THREAD

**Issue by gyss** [akoenig/angular-deckgrid#74]
Hi,
it'd be nice if deckgrid supported different column widths.
You can check an example of what I mean [here](http://masonry.desandro.com/options.html).

**Comment by akoenig** [comment]
I'm not sure if I understand right, but you're able to define the column width within your CSS.

**Comment by gyss** [comment]
Yes, but I explained it wrong. The idea is to have certain elements that can take more than one column.
For example if we have two columns of 200px width, could I have an element of 400px that take up both columns?

**Comment by gyss** [comment]
This is the idea I was trying to explain: 
![Masonry](http://i61.tinypic.com/29yp6dz.png)

**Comment by Citrullin** [comment]
That's not possible with Deckgrid. Deckgrid works a little bit different as Masonry. Masonry gets the elements (after they are rendered) and fix the spaces between this elements. Deckgrid get the data before it's rendered made the columns with the same width and insert the elements equally over all columns. Deckgrid is only the fix for old browser who doesn't support CSS 3 Columns.
Example of CSS 3 Columns: http://cssdeck.com/labs/css-only-pinterest-style-columns-layout

**Comment by gyss** [comment]
Okay!

thanks Citrullin
